version: '3'

services:

  webapp:
    build:
      context: backend
      dockerfile: Dockerfile-dev
    depends_on:
      - redis
      - mysql
      - elasticsearch
    volumes:
      - ./backend/:/backend
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    command:
      - /bin/sh
      - -c
      - |
        # 确定服务启动
        python3 /backend/wait-for-it.py mysql:3306 elasticsearch:9200 redis:6379 coverage run --source='.' runtests.py
        coverage report
        flake8 . --ignore E501,F401

  celery:
    build:
      context: backend
      dockerfile: Dockerfile-dev
    depends_on:
      - redis
      - mysql
      - elasticsearch
    volumes:
      - ./backend/:/backend
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    command: 
      - /bin/sh
      - -c
      - |
        # 确定服务启动
        python3 /backend/wait-for-it.py mysql:3306 elasticsearch:9200 redis:6379 celery -A my_blog worker -l info -P eventlet

  redis:
    image: "redis:5.0-alpine"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    command:
      - /bin/sh
      - -c
      - |
        # 设置时区
        ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo Asia/Shanghai > /etc/timezone
        apk add tzdata
        redis-server

  mysql:
    image: mysql:8.0
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./volumn/mysql/data:/var/lib/mysql
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    environment:
      # 根目录密码默认123456，可以根据需求改密码
      # 修改的时候要同时修改serect文件的密码
      - MYSQL_ROOT_PASSWORD=123456
      # 这个选项会自动创建数据库
      - MYSQL_DATABASE=my_blog
      - TZ=Asia/Shanghai

  elasticsearch:
    # 测试时不挂载volumn
    build: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - "ES_JAVA_OPTS=-Xms250m -Xmx250m"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
