version: '3'

services:
  webapp:
    build: backend
    ports:
      - "8800:8000"

    depends_on:
      - redis
      - mysql

  redis:
    image: "redis:alpine"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
