version: "3"

services:

  webapp:
    build: backend
    image: my_blog_webapp
    container_name: my_blog_webapp_container
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    command:
      - /bin/sh
      - -c
      - |
        python3 /backend/wait-for-it.py mysql:3306 elasticsearch:9200 redis:6379
        # 保持容器不退出
        tail -f /dev/null
    volumes:
      - ./backend/:/backend
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./volumn/mysql/data:/var/lib/mysql
    environment:
      # 根目录密码默认123456，可以根据需求改密码
      # 修改的时候要同时修改secret文件的密码
      - MYSQL_ROOT_PASSWORD=123456
      # 这个选项会自动创建数据库
      - MYSQL_DATABASE=my_blog
      - TZ=Asia/Shanghai
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"

  elasticsearch:
    build: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - "ES_JAVA_OPTS=-Xms400m -Xmx400m"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"

  redis:
    image: "redis:5.0-alpine"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    restart: always

  celery:
    build: backend
    depends_on:
      - redis
      - mysql
      - elasticsearch
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    volumes:
      - ./backend/:/backend
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        # 确定服务启动
        python3 /backend/wait-for-it.py mysql:3306 elasticsearch:9200 redis:6379 celery -A my_blog worker -l info -P eventlet
