version: "3"

services:

  webapp:
    build: backend
    image: my_blog_webapp
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    volumes:
      - ./backend/:/backend
    depends_on:
      - mysql
    command:
      - /bin/sh
      - -c
      - |
        # 确定服务启动
        python3 /backend/wait-for-it.py mysql:3306
        /usr/local/bin/gunicorn my_blog.wsgi --bind 0.0.0.0:8000
    networks:
      - my-blog-network
    restart: always

  nginx:
    image: nginx:1.17
    networks:
      - my-blog-network
    depends_on:
      - webapp
    volumes:
      - ./volumn/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static
    ports:
      - "8002:80"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    restart: always

  mysql:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./volumn/mysql/data:/var/lib/mysql
    environment:
      # 根目录密码默认123456，可以根据需求改密码
      # 修改的时候要同时修改secret文件的密码
      - MYSQL_ROOT_PASSWORD=123456
      # 这个选项会自动创建数据库
      - MYSQL_DATABASE=my_blog
      - TZ=Asia/Shanghai
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    networks:
      - my-blog-network

networks:
   my-blog-network:
     driver: bridge
