version: "3"

services:

  webapp:
    command:
      - /bin/sh
      - -c
      - |
        # 确定服务启动
        python3 /backend/wait-for-it.py mysql:3306 elasticsearch:9200 redis:6379
        /usr/local/bin/gunicorn my_blog.wsgi --bind 0.0.0.0:8000
    networks:
      - my-blog-network
    depends_on:
      - redis
      - mysql
      - elasticsearch
    restart: always

  celery:
    build: backend
    depends_on:
      - redis
      - mysql
      - elasticsearch
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    volumes:
      - ./backend/:/backend
    restart: always
    networks:
      - my-blog-network
    command: 
      - /bin/sh
      - -c
      - |
        # 确定服务启动
        python3 /backend/wait-for-it.py mysql:3306 elasticsearch:9200 redis:6379 celery -A my_blog worker -l info -P eventlet

  redis:
    image: "redis:5.0-alpine"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    networks:
      - my-blog-network
    restart: always

  elasticsearch:
    build: elasticsearch
    networks:
      - my-blog-network
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - "ES_JAVA_OPTS=-Xms400m -Xmx400m"
    volumes:
      - ./volumn/elasticsearch/data:/usr/share/elasticsearch/data
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    restart: always

  nginx:
    image: nginx:1.17
    networks:
      - my-blog-network
    depends_on:
      - redis
      - elasticsearch
      - celery
      - webapp
    volumes:
      - ./volumn/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static
    ports:
      - "8002:80"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    restart: always

  mysql:
    networks:
      - my-blog-network

networks:
   my-blog-network:
     driver: bridge
