version: '3'

services:

  webapp:
    command: 
      - /bin/sh
      - -c
      - |
        # 确定服务启动
        python3 /backend/wait-for-it.py mysql:3306 elasticsearch:9200 redis:6379 python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8890:8000"
    depends_on:
      - redis
      - mysql
      - elasticsearch

  celery:
    build: backend
    depends_on:
      - redis
      - mysql
      - elasticsearch
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    command: 
      - /bin/sh
      - -c
      - |
        # 确定服务启动
        python3 /backend/wait-for-it.py mysql:3306 elasticsearch:9200 redis:6379 celery -A my_blog worker -l info -P eventlet

  redis:
    image: "redis:5.0-alpine"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    command:
      - /bin/sh
      - -c
      - |
        # 设置时区
        ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo Asia/Shanghai > /etc/timezone
        apk add tzdata
        redis-server

  elasticsearch:
    build: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - "ES_JAVA_OPTS=-Xms250m -Xmx250m"
    volumes:
      - ./volumn/elasticsearch/data:/usr/share/elasticsearch/data
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '10'
    ports:
      - "9200:9200"
      - "9300:9300"
