# Generated by Django 2.1.7 on 2019-03-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('author', models.CharField(max_length=256, verbose_name='作者')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('last_change_time', models.DateTimeField(auto_now_add=True, verbose_name='最后修改')),
                ('brief', models.CharField(max_length=256, verbose_name='简介')),
                ('content', models.TextField(verbose_name='正文')),
                ('read_count', models.IntegerField(verbose_name='阅读数')),
                ('like_count', models.IntegerField(verbose_name='喜欢数')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='分类')),
                ('father_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30, verbose_name='标题')),
                ('password', models.CharField(max_length=30, verbose_name='作者')),
                ('username', models.DateTimeField(verbose_name='创建时间')),
                ('phone', models.CharField(max_length=30, verbose_name='最后修改')),
                ('email', models.EmailField(max_length=254, verbose_name='Email地址')),
                ('superuser', models.BooleanField(verbose_name='是否是超级用户')),
                ('author', models.BooleanField(verbose_name='是否是作者')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(verbose_name='关于我页面内容')),
                ('website_name', models.CharField(max_length=10, verbose_name='网站名')),
                ('ICP_number', models.CharField(max_length=20, verbose_name='备案号')),
                ('website_image', models.CharField(max_length=256, verbose_name='网站头像')),
                ('ad_1', models.CharField(max_length=256, verbose_name='主页侧栏图片1')),
                ('ad_2', models.CharField(max_length=256, verbose_name='主页侧栏图片2')),
                ('github', models.CharField(max_length=256, verbose_name='Github地址')),
                ('email', models.CharField(max_length=256, verbose_name='邮箱地址')),
                ('Friendship_link', models.CharField(max_length=2000, verbose_name='友情链接地址')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tabs',
            field=models.ManyToManyField(to='main.Tab'),
        ),
    ]
