# Generated by Django 2.2 on 2019-04-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='blog',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
    ]
