# Generated by Django 2.2 on 2019-05-07 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tab',
            options={'ordering': ['id']},
        ),
    ]
