# Generated by Django 2.2 on 2019-04-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='喜欢数'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='电话号码'),
        ),
    ]
