# Generated by Django 2.2 on 2019-05-07 02:51

from django.db import migrations
import main.manager.user


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190507_1028'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main.manager.user.CustomUserManager()),
            ],
        ),
    ]
