# Generated by Django 2.2 on 2019-04-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190409_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='电话号码'),
        ),
    ]
