# Generated by Django 2.2 on 2019-04-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190403_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitemanage',
            name='ad_1',
            field=models.URLField(verbose_name='主页侧栏图片1'),
        ),
        migrations.AlterField(
            model_name='websitemanage',
            name='ad_2',
            field=models.URLField(verbose_name='主页侧栏图片2'),
        ),
        migrations.AlterField(
            model_name='websitemanage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='websitemanage',
            name='github',
            field=models.URLField(verbose_name='Github地址'),
        ),
    ]
