# Generated by Django 2.2 on 2019-04-19 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190410_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitemanage',
            old_name='Friendship_link',
            new_name='friendship_link',
        ),
    ]
