# Generated by Django 2.2 on 2019-05-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190510_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='日期')),
                ('like_count', models.IntegerField(verbose_name='统计')),
                ('comment_count', models.IntegerField(verbose_name='统计')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=10, verbose_name='标题')),
                ('city', models.CharField(max_length=20, verbose_name='标题')),
            ],
        ),
        migrations.CreateModel(
            name='RegionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='日期')),
                ('count', models.IntegerField(verbose_name='统计')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Region')),
            ],
        ),
    ]
