# Generated by Django 2.2 on 2019-04-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190404_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemanage',
            name='demo_model',
            field=models.BooleanField(default=False, verbose_name='是否开放demo模式'),
        ),
        migrations.AddField(
            model_name='websitemanage',
            name='open_register',
            field=models.BooleanField(default=False, verbose_name='是否开放注册'),
        ),
    ]
