# Generated by Django 2.2 on 2019-04-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190419_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemanage',
            name='ad_1_url',
            field=models.URLField(default='www.11111.com', verbose_name='主页侧栏图片1广告url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitemanage',
            name='ad_2_url',
            field=models.URLField(default='www.22222.com', verbose_name='主页侧栏图片2广告url'),
            preserve_default=False,
        ),
    ]
