# Generated by Django 2.2 on 2019-05-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_daterecord_region_regionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterecord',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论统计'),
        ),
        migrations.AlterField(
            model_name='daterecord',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='喜爱统计'),
        ),
        migrations.AlterField(
            model_name='regionrecord',
            name='count',
            field=models.IntegerField(default=0, verbose_name='统计'),
        ),
    ]
