# Generated by Django 2.2 on 2019-05-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190513_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='daterecord',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读统计'),
        ),
    ]
