# Generated by Django 2.2 on 2019-04-22 06:53

import django.contrib.auth.models
from django.db import migrations
import main.manager.user


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190419_1553'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('custom_objects', main.manager.user.CustomUserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
