# Generated by Django 2.2 on 2019-05-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190514_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.URLField(default='', verbose_name='头像'),
        ),
    ]
