# Generated by Django 2.2 on 2019-05-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo_user',
            field=models.BooleanField(default=False, verbose_name='是否是使用用户'),
        ),
    ]
